name: MLP

INPUT_OUTPUT:
  coord_mode: 2                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 0: [0, 1]^2,  1: [-1, 1]^2

NET:
  num_layers: 3
  dim_hidden: 64
  use_bias: True
