TRAIN_CONFIGS:
  out_dir: siren_audio
  iterations: 5000
  save_interval: 100
  mt_save_interval: 100
  device: cuda:0
  seed: 42
  sampling_path: sampling_history.pkl
  loss_path: loss_history.pkl
  save_name: siren
  no_io: 0

EXP_CONFIGS:
  scheduler_type: cosine
  mt_ratio: 0.2
  optimizer_type: adam
  lr_scheduler_type: cosine
  strategy_type: dense
  top_k: 1

NETWORK_CONFIGS:
  lr: 1e-4
  data_range: 0
  coord_mode: 2
  rff_std: 10

DATASET_CONFIGS:
  data_type: audio
  sample_idx: 0
  num_secs: 2

WANDB_CONFIGS:
  use_wandb: 1
  wandb_project: mt_visualization
  wandb_entity: hku_inr
  group: siren

defaults:
  - model_config: siren

# hydra logging
hydra:
  run:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}
    
  sweep:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}/${hydra.job.name}
    subdir: ${hydra.job.num}