TRAIN_CONFIGS:
  out_dir: siren
  lr: 1e-3
  iterations: 5000
  save_interval: 100
  device: cuda:0
  seed: 42
  mt_ratio: 0.2

EXP_CONFIGS:
  scheduler_type: step

DATASET_CONFIGS:
  data_type: image
  file_path: ../datasets/kodak/kodim01.png
  color_mode: RGB              # RGB or L (grayscale)
  img_size: null


WANDB_CONFIGS:
  use_wandb: 1
  wandb_project: mt_exploration
  wandb_entity: hku_inr
  group: scheduler

defaults:
  - model_config: siren

# hydra logging
hydra:
  run:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}
    
  sweep:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}/${hydra.job.name}
    subdir: ${hydra.job.num}