TRAIN_CONFIGS:
  out_dir: siren
  iterations: 500
  save_interval: 10
  mt_save_interval: 10
  device: cuda:2
  seed: 42
  sampling_path: sampling_history.pkl
  loss_path: loss_history.pkl

EXP_CONFIGS:
  scheduler_type: constant
  mt_ratio: 0.2
  optimizer_type: adam
  lr_scheduler_type: constant
  strategy_type: dense
  top_k: 1

NETWORK_CONFIGS:
  lr: 1e-3
  data_range: 0
  coord_mode: 2
  rff_std: 10
  num_layers: 5
  dim_hidden: 512

DATASET_CONFIGS:
  data_type: megapixel
  file_path: ../datasets/megapixels/pluto.png
  color_mode: RGB              # RGB or L (grayscale)
  img_size: [8192, 8192]
  max_coords: 400000
  pool_ratio: 1.0

WANDB_CONFIGS:
  use_wandb: 1
  wandb_project: mt_exploration
  wandb_entity: hku_inr
  group: dynamics

defaults:
  - model_config: siren

# hydra logging
hydra:
  run:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}
    
  sweep:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}/${hydra.job.name}
    subdir: ${hydra.job.num}